
title: Alejandro Gómez de la Muñoza
url: 'agdelamunoza.github.io'
baseurl: '' 
style: styles-2

#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Alejandro Gómez de la Muñoza
tagline: Filólogo, traductor y localizador
pic: profile.png

#sidebar links
email: alejandrogdelamunoza@outlook.com
phone:
website: agdelamunoza.es
linkedin: agdelamunuza
github: agdelamunoza
twitter: '@agdelamunoza'

