
title: Alejandro Gómez de la Muñoza
url: 'agdelamunoza.github.io'
baseurl: '' 
style: styles-2

#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Alan Doe
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: alan.doe@website.com
phone: 012 345 6789
website: blog.webjeda.com
linkedin: alandoe
github: alandoe
twitter: '@twittername'

