# Site settings
title: Alejandro Gómez de la Muñoza
blog_title: Alejandro G. de la Muñoza
header-img: img/home-bg.jpg
email: 
copyright_name: Alejandro Gómez de la Muñoza
description: "Audiovisual Translator • Video Game Localizer"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: 
disqus_url: 
github_username: 
facebook_username: 
stackoverflow_username: 
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
